spring:
  application:
    name: reservationservice
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: springuser
    password: qwerty123
spring.datasource.url: jdbc:mysql://localhost:3306/wetwet
cors.urls: http://localhost:3000
